import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { ESPACE_PRO_DEMO_URL, ESPACE_PRO_URL } from "@/lib/espacePro";

const portalDir = path.resolve(__dirname, "../../public/espace-pro");
const read = (file: string) => fs.readFileSync(path.join(portalDir, file), "utf8");
const exists = (file: string) => fs.existsSync(path.join(portalDir, file));

describe("professional portal bundle (public/espace-pro)", () => {
  const html = read("index.html");

  it("is reachable through the URL used by the React routes", () => {
    expect(ESPACE_PRO_URL).toBe("/espace-pro/index.html");
    expect(ESPACE_PRO_DEMO_URL).toBe("/espace-pro/index.html?demo=1");
    expect(exists("index.html")).toBe(true);
  });

  it("was generated by the importer and contains no inline code or base64 payloads", () => {
    expect(html).toContain("Generated by scripts/import-portal.mjs");
    expect(html).not.toMatch(/<style[\s>]/);
    expect(html).not.toMatch(/<script(?![^>]*\ssrc=)[^>]*>/);
    expect(html).not.toMatch(/data:[a-z/+.-]+;base64,/);
    expect(html.length).toBeLessThan(20_000);
  });

  it("links every referenced local file to an existing one", () => {
    const refs = [...html.matchAll(/(?:src|href)="([^"]+)"/g)].map((m) => m[1]).filter((u) => !/^(https?:|data:|\/|#)/.test(u));
    expect(refs.length).toBeGreaterThan(30);
    for (const ref of refs) expect(exists(ref), `${ref} is missing`).toBe(true);
  });

  it("loads layers in source order, config first and production layer last", () => {
    const scripts = [...html.matchAll(/<script src="([^"]+)"><\/script>/g)].map((m) => m[1]);
    expect(scripts[0]).toBe("portal.config.js");
    expect(scripts.at(-1)).toBe("portal.launch.js");
    const layers = scripts.filter((s) => s.startsWith("js/"));
    expect(layers[0]).toBe("js/00-core.js");
    expect(layers).toEqual([...layers].sort());
    expect(layers.length).toBe(fs.readdirSync(path.join(portalDir, "js")).filter((f) => f.endsWith(".js")).length);
  });

  it("ships production metadata: stable title, noindex, real manifest and icons", () => {
    expect(html).toContain("<title>RENOVO CRETE — Professional Portal</title>");
    expect(html).toContain('<meta name="robots" content="noindex, nofollow">');
    expect(html).toContain('<link rel="manifest" href="manifest.webmanifest">');
    const manifest = JSON.parse(read("manifest.webmanifest"));
    expect(manifest.start_url).toBe("./index.html");
    for (const icon of manifest.icons) expect(exists(icon.src), `${icon.src} is missing`).toBe(true);
  });

  it("precaches every shipped file in the service worker", () => {
    const sw = read("sw.js");
    const precache: string[] = JSON.parse(/const PRECACHE = (\[[\s\S]*?\]);/.exec(sw)![1]);
    for (const file of precache) expect(exists(file), `${file} is missing`).toBe(true);
    for (const file of ["./index.html", "./portal.css", "./portal.config.js", "./portal.launch.js", "./js/00-core.js"]) expect(precache).toContain(file);
    expect(sw).toMatch(/const CACHE = "renovo-portal-[0-9a-f]{10}"/);
  });

  it("keeps print templates inside the JavaScript layers (styles were not ripped out of JS strings)", () => {
    expect(read("js/00-core.js")).toMatch(/<style>body\{font-family:Arial;padding:20px\}/);
    expect(read("js/05-v12-access-pwa.js")).toMatch(/<style>body\{font:11px Arial/);
    expect(read("portal.css")).not.toMatch(/body\{font:11px Arial/);
  });

  it("provides the system diagrams referenced by the catalog layers", () => {
    const core = read("js/00-core.js");
    const images = [...new Set([...core.matchAll(/'(assets\/hermetic-[a-z-]+\.png)'/g)].map((m) => m[1]))];
    expect(images.length).toBe(3);
    for (const img of images) expect(exists(img), `${img} is missing`).toBe(true);
  });

  it("exposes layer symbols that later layers depend on", () => {
    const v25 = read("js/17-v25-targeted.js");
    expect(v25).toContain("try{window.rc25S=rc25S}catch(e){}");
    expect(v25).toContain("try{window.rc25OpenMdComposer=rc25OpenMdComposer}catch(e){}");
  });

  it("robots.txt keeps the portal out of search engines", () => {
    const robots = fs.readFileSync(path.resolve(__dirname, "../../public/robots.txt"), "utf8");
    expect(robots).toContain("Disallow: /espace-pro");
  });
});
